default:
  image: julia:1.8.5
  before_script:
  - git clone git@gitlabph.physik.fu-berlin.de:julia-frg/SpinFRGLattices.jl.git 
  - julia --project=test -e 'import Pkg; Pkg.build()' # build the package

test:1.8.5:
  image: julia:1.8.5
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage=true)" # test the package
  #  - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()' # Setup coverage environment
  #  - julia --project=test/coverage test/coverage/coverage_summary.jl # run coverage summary
  #coverage: '/Code coverage: \d+\.\d+/' # Regex expression to determine coverage
  only:
  - master

